test:
  script: cat index.php file2.txt | grep -q 'Hello'
  

# Select image from https://hub.docker.com/_/php/  
image: php:7.2-apache 


before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install mysql driver
- docker-php-ext-install pdo_mysql
- cd tests
# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

cache:
  paths:
  - vendor/
    