test:
  script: echo 'start'
  


image: registry.gitlab.com/tatyanayanova/testselenium:latest

cache:
  paths:
  - vendor/

before_script:    
    - cd tests    
    # Install composer
    - curl -sS https://getcomposer.org/installer | php
    # Install all project dependencies
    - php composer.phar install
    - cd /
    - ls