test:
  script: echo 'start'
  

# Select image from https://hub.docker.com/_/php/  
image: https://gitlab.com/TatyanaYanova/testSelenium

cache:
  paths:
  - vendor/

before_script:
    - cd tests    
    # Install all project dependencies
    - php composer install
    - cd /
    - ls