test:
  script: echo 'start'
  

# Select image from https://hub.docker.com/_/php/  
image: php:7.2-apache 

cache:
  paths:
  - vendor/

before_script:
    # Install git, the php image doesn't have installed
    - apt-get update -yqq
    - apt-get install git -yqq
    # Install mysql driver
    - docker-php-ext-install pdo_mysql

    - cd tests
    # Install composer
    - curl -sS https://getcomposer.org/installer | php
    # Install all project dependencies
    - php composer.phar install
    #установить chromedriver
    - apt-get install wget
    - apt-get install unzip
    - wget -O chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - chown root:root chromedriver
    - chmod 0755 chromedriver
    #Загрузкa selenium-server
    - wget -O selenium.jar https://goo.gl/UzaKCo
    #устанавливаем Java
    - apt-get update
    
    - apt-get install default-jre

    - java -Dwebdriver.chrome.driver=chromedriver -jar selenium.jar -debug