test:
  script: cat index.php file2.txt | grep -q 'Hello'
  

# Select image from https://hub.docker.com/_/php/  
image: php:7.2-apache 

cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install mysql driver
- docker-php-ext-install pdo_mysql

# Install composer
- curl -sS https://getcomposer.org/installer | php
- sudo mv composer.phar /usr/local/bin/composer
- composer global require fxp/composer-asset-plugin

- cd tests
# Install all project dependencies
- php composer.phar install

     