test:
  script: echo 'start'
  


image: registry.gitlab.com/tatyanayanova/testselenium:latest

cache:
  paths:
  - vendor/

before_script:    
    - cd tests    
    # Install all project dependencies
    - php composer install
    - cd /
    - ls